AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-ses

  Sample SAM Template for aws-lambda-ses

Globals:
  Function:
    Timeout: 10
    MemorySize: 1024

Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: send_email/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SendEmailFunction:
          Type: Api 
          Properties:
            Path: /send_email
            Method: post

Outputs:
  
  SendEmailFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SendEmailFunction.Arn

